### PR TITLE
Add pt-br translations

### PR DESCRIPTION
**Pull request by ZJRDroid**
### Guidelines 

1. You must run the `spotlessApply` task before committing, either through Android Studio or with `./gradlew spotlessApply`.
2. A PR should be focused and contained. If you are changing multiple unrelated things, they should be in separate PRs.
3. A PR should fix a bug or solve a problem - something that only you would use is not necessarily something that should be published.
4. Give your PR a detailed title and description - look over your code one last time before actually creating the PR. Give it a self-review.

**If you do not follow the guidelines, your PR will be rejected.**

### CODE REVIEW

**Comment by ZJRDroid** [comment]
> I think you missed the strings-about.xml file

done

**Comment by afollestad** [comment]
Thank you!

**Comment by naman14** [comment]
@ZJRDroid will it possible if you can update the translations to include the newly added strings that were added today?

**Comment by ZJRDroid** [comment]
> @ZJRDroid will it possible if you can update the translations to include the newly added strings that were added today?

Updated!

**Comment by naman14** [comment]
Thanks!

**Pull request merged**
